version: '3'

networks:
  chain:
    ipam:
      driver: default
  ipfs:
    ipam:
      driver: default
  cust:
    ipam:
      driver: default

services:
  node-alice:
    image: ghcr.io/digicatapult/vitalam-node:v2.0.0
    container_name: node-alice
    hostname: node-alice
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    volumes:
      - ../data/cust/node:/data
    restart: on-failure
    command: ./run.sh
    environment:
      - IDENTITY=${IDENTITY_ALICE}
      - RPC=${RPC}
      - CORS=${CORS}
      - WS=${WS}
      - NODEKEY=${NODE_ALICE_KEY}
      - BOOTNODES=/dns4/node-bob/tcp/30333/p2p/${NODE_BOB_PEERID},/dns4/node-charlie/tcp/30333/p2p/${NODE_CHARLIE_PEERID}
    networks: ['chain', 'cust']

  ipfs-alice:
    image: vitalam-alpine-ipfs:latest
    container_name: ipfs-alice
    hostname: ipfs-alice
    build: { 'context': './', 'dockerfile': 'Dockerfile-ipfs', 'args': { 'VER': 'v0.4.23' } }
    ports:
      - 5001:5001
      - 4001:4001
      - 8080:8080
    environment:
      - PEERID=${IPFS_ALICE_PEERID}
      - PRIVKEY=${IPFS_ALICE_PRIVKEY}
      - BOOTNODES=/dns4/ipfs-bob/tcp/4001/ipfs/${IPFS_BOB_PEERID},/dns4/ipfs-charlie/tcp/4001/ipfs/${IPFS_CHARLIE_PEERID}
    volumes:
      - ../data/cust/ipfs:/data
    restart: on-failure
    command: ./run.sh
    networks: ['ipfs', 'cust']

  api-alice:
    image: ghcr.io/digicatapult/vitalam-api:v2.0.1
    container_name: api-alice
    hostname: api-alice
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - API_HOST=${NODE_ALICE_HOST}
      - API_PORT=9944
      - USER_URI=${API_ALICE_WALLET_USER_URI}
      - IPFS_HOST=${IPFS_ALICE_HOST}
      - IPFS_PORT=5001
      - LOG_LEVEL=debug
      - AUTH_JWKS_URI=${API_JWKS_URI}
      - AUTH_AUDIENCE=${API_AUTH_AUDIENCE}
      - AUTH_ISSUER=${API_AUTH_ISSUER}
      - AUTH_TOKEN_URL=${API_AUTH_TOKEN_URL}
    restart: on-failure
    networks: ['cust']

  react-alice:
    container_name: react-alice
    hostname: react-alice
    build:
      context: '../'
      dockerfile: 'Dockerfile'
      args:
        - REACT_APP_VITALAM_DEMO_PERSONA=cust
        - REACT_APP_API_HOST=${REACT_API_ALICE_HOST}
        - REACT_APP_API_PORT=${REACT_API_ALICE_PORT}
        - REACT_APP_SUBSTRATE_HOST=${REACT_API_ALICE_SUBSTRATE_HOST}
        - REACT_APP_SUBSTRATE_PORT=${REACT_API_ALICE_SUBSTRATE_PORT}
        - REACT_APP_AUTH_CLIENT_ID=${REACT_API_AUTH_CLIENT_ID}
        - REACT_APP_AUTH_CLIENT_SECRET=${REACT_API_AUTH_CLIENT_SECRET}
    ports:
      - 8001:3000
    restart: on-failure
    networks: ['cust']
