version: '3'

networks:
  chain:
    ipam:
      driver: default
  ipfs:
    ipam:
      driver: default
  lab:
    ipam:
      driver: default

services:
  node-charlie:
    image: ghcr.io/digicatapult/vitalam-node:v2.0.0
    container_name: node-charlie
    hostname: node-charlie
    ports:
      - 30335:30333
      - 9946:9944
      - 9935:9933
    volumes:
      - ../data/lab/node:/data
    restart: on-failure
    command: ./run.sh
    environment:
      - IDENTITY=${IDENTITY_CHARLIE}
      - RPC=${RPC}
      - CORS=${CORS}
      - WS=${WS}
      - NODEKEY=${NODE_CHARLIE_KEY}
      - BOOTNODES=/dns4/node-alice/tcp/30333/p2p/${NODE_ALICE_PEERID},/dns4/node-bob/tcp/30333/p2p/${NODE_BOB_PEERID}
    networks: ['chain', 'lab']

  ipfs-charlie:
    image: vitalam-alpine-ipfs:latest
    container_name: ipfs-charlie
    hostname: ipfs-charlie
    build: { 'context': './', 'dockerfile': 'Dockerfile-ipfs', 'args': { 'VER': 'v0.4.23' } }
    ports:
      - 5003:5001
      - 4003:4001
      - 8082:8080
    environment:
      - PEERID=${IPFS_CHARLIE_PEERID}
      - PRIVKEY=${IPFS_CHARLIE_PRIVKEY}
      - BOOTNODES=/dns4/ipfs-alice/tcp/4001/ipfs/${IPFS_ALICE_PEERID},/dns4/ipfs-bob/tcp/4001/ipfs/${IPFS_BOB_PEERID}
    volumes:
      - ../data/lab/ipfs:/data
    restart: on-failure
    command: ./run.sh
    networks: ['ipfs', 'lab']

  api-charlie:
    image: ghcr.io/digicatapult/vitalam-api:v2.0.1
    container_name: api-charlie
    hostname: api-charlie
    ports:
      - 3003:3001
    environment:
      - PORT=3001
      - API_HOST=${NODE_CHARLIE_HOST}
      - API_PORT=9944
      - USER_URI=${API_CHARLIE_WALLET_USER_URI}
      - IPFS_HOST=${IPFS_CHARLIE_HOST}
      - IPFS_PORT=5001
      - LOG_LEVEL=debug
      - AUTH_JWKS_URI=${API_JWKS_URI}
      - AUTH_AUDIENCE=${API_AUTH_AUDIENCE}
      - AUTH_ISSUER=${API_AUTH_ISSUER}
      - AUTH_TOKEN_URL=${API_AUTH_TOKEN_URL}
    restart: on-failure
    networks: ['lab']

  react-charlie:
    container_name: react-charlie
    hostname: react-charlie
    build:
      context: '../'
      dockerfile: 'Dockerfile'
      args:
        - REACT_APP_VITALAM_DEMO_PERSONA=lab
        - REACT_APP_API_HOST=${REACT_API_CHARLIE_HOST}
        - REACT_APP_API_PORT=${REACT_API_CHARLIE_PORT}
        - REACT_APP_SUBSTRATE_HOST=${REACT_API_CHARLIE_SUBSTRATE_HOST}
        - REACT_APP_SUBSTRATE_PORT=${REACT_API_CHARLIE_SUBSTRATE_PORT}
        - REACT_APP_AUTH_CLIENT_ID=${REACT_API_AUTH_CLIENT_ID}
        - REACT_APP_AUTH_CLIENT_SECRET=${REACT_API_AUTH_CLIENT_SECRET}
    ports:
      - 8003:3000
    restart: on-failure
    networks: ['lab']
