version: '3'

networks:
  chain:
    ipam:
      driver: default
  ipfs:
    ipam:
      driver: default
  cust:
    ipam:
      driver: default

services:
  node-alice:
    image: ghcr.io/digicatapult/vitalam-node:v2.5.1
    container_name: node-alice
    command: /bin/sh -c "
      ./vitalam-node
      --base-path /data/
      --alice
      --node-key ${NODE_ALICE_KEY}
      --bootnodes /dns4/node-bob/tcp/30333/p2p/${NODE_BOB_PEERID}
      --bootnodes /dns4/node-charlie/tcp/30333/p2p/${NODE_CHARLIE_PEERID}
      --chain local
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all"
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    volumes:
      - ../data/cust/node:/data
    restart: on-failure
    networks: ['chain', 'cust']

  ipfs-alice:
    image: ghcr.io/digicatapult/vitalam-ipfs:v1.0.0
    container_name: ipfs-alice
    ports:
      - 5001:5001
      - 4001:4001
    volumes:
      - ../data/cust/ipfs:/ipfs
    environment:
      - NODE_HOST=node-alice
    restart: on-failure
    networks: ['ipfs', 'cust']

  api-alice:
    image: ghcr.io/digicatapult/vitalam-api:v2.4.1
    container_name: api-alice
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - API_HOST=node-alice
      - API_PORT=9944
      - USER_URI=${API_ALICE_WALLET_USER_URI}
      - IPFS_HOST=ipfs-alice
      - IPFS_PORT=5001
      - LOG_LEVEL=trace
      - AUTH_JWKS_URI=${API_JWKS_URI}
      - AUTH_AUDIENCE=${API_AUTH_AUDIENCE}
      - AUTH_ISSUER=${API_AUTH_ISSUER}
      - AUTH_TOKEN_URL=${API_AUTH_TOKEN_URL}
    restart: on-failure
    networks: ['cust']

  react-alice:
    container_name: react-alice
    build:
      context: '../'
      dockerfile: 'Dockerfile'
      args:
        - REACT_APP_VITALAM_DEMO_PERSONA=cust
        - REACT_APP_API_HOST=${REACT_API_ALICE_HOST}
        - REACT_APP_API_PORT=${REACT_API_ALICE_PORT}
        - REACT_APP_SUBSTRATE_HOST=${REACT_API_ALICE_SUBSTRATE_HOST}
        - REACT_APP_SUBSTRATE_PORT=${REACT_API_ALICE_SUBSTRATE_PORT}
        - REACT_APP_AUTH_CLIENT_ID=${REACT_API_AUTH_CLIENT_ID}
        - REACT_APP_AUTH_CLIENT_SECRET=${REACT_API_AUTH_CLIENT_SECRET}
    ports:
      - 8001:3000
    restart: on-failure
    networks: ['cust']
